/**
 * FeatureStore.js — Phase 2 Batch 2
 *
 * ML-ready feature records.
 * One record per completed booking.
 * Automatically generated by featureService after booking closes.
 *
 * targetLabel is null — to be assigned by future labelling pipeline.
 * All snapshot fields capture point-in-time metrics to avoid data leakage.
 */

import mongoose from 'mongoose';

const featureStoreSchema = new mongoose.Schema(
  {
    // ─── Primary Keys ────────────────────────────────────────────────────────
    bookingId:  { type: mongoose.Schema.Types.ObjectId, ref: 'Booking', required: true, unique: true },
    customerId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    workerId:   { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    serviceId:  { type: mongoose.Schema.Types.ObjectId, ref: 'Service' },

    // ─── Booking Features ────────────────────────────────────────────────────
    city:        { type: String, trim: true },
    area:        { type: String, trim: true },
    category:    { type: String, trim: true },
    subCategory: { type: String, trim: true },
    price:       { type: Number },
    isEmergency: { type: Boolean, default: false },

    // Scheduled hour of day (0-23) and day of week (0=Sun)
    scheduledHour:      { type: Number },
    scheduledDayOfWeek: { type: Number },

    // ─── Timing Features ─────────────────────────────────────────────────────
    distanceKm:          { type: Number }, // worker to customer
    arrivalTimeMs:       { type: Number }, // accepted → arrived
    responseTimeMs:      { type: Number }, // assigned → accepted
    completionTimeMs:    { type: Number }, // started → completed

    // ─── Rating Features ─────────────────────────────────────────────────────
    ratingBreakdown: {
      overall:        { type: Number },
      quality:        { type: Number },
      punctuality:    { type: Number },
      communication:  { type: Number },
      professionalism:{ type: Number },
      cleanliness:    { type: Number },
      valueForMoney:  { type: Number },
    },

    // ─── Snapshot Features (point-in-time to prevent leakage) ───────────────
    workerMetricsSnapshot: {
      completionRate:     { type: Number },
      acceptanceRate:     { type: Number },
      avgRating:          { type: Number },
      totalCompletions:   { type: Number },
      avgResponseTimeMs:  { type: Number },
      avgArrivalTimeMs:   { type: Number },
    },
    customerMetricsSnapshot: {
      totalBookings:      { type: Number },
      completedBookings:  { type: Number },
      avgSpend:           { type: Number },
      isRepeat:           { type: Boolean },
    },
    trustProfileSnapshot: {
      completionRate:     { type: Number },
      complaintRate:      { type: Number },
      refundRate:         { type: Number },
      averageRating:      { type: Number },
      adminWarnings:      { type: Number },
    },
    complaintSnapshot: {
      hadComplaint:       { type: Boolean, default: false },
      complaintCategory:  { type: String },
    },

    // ─── Timeline Summary ─────────────────────────────────────────────────────
    timelineSummary: {
      milestones:    [{ type: String }], // list of event names in order
      totalDurationMs: { type: Number }, // created → closed
    },

    // ─── Target Label ────────────────────────────────────────────────────────
    // null until future labelling pipeline assigns it
    targetLabel: { type: mongoose.Schema.Types.Mixed, default: null },

    createdAt: { type: Date, default: Date.now },
  },
  { timestamps: false }
);

// Indexes
featureStoreSchema.index({ workerId: 1 });
featureStoreSchema.index({ customerId: 1 });

featureStoreSchema.index({ category: 1 });
featureStoreSchema.index({ city: 1, category: 1 });
featureStoreSchema.index({ createdAt: -1 });
featureStoreSchema.index({ targetLabel: 1 }, { sparse: true });

export default mongoose.model('FeatureStore', featureStoreSchema);
